SQLALCHEMY_DATABASE_URI: postgresql://postgres:ow2ptLo5"^BjVB=J(?>"O@rYp@217.182.87.226/database?connect_timeout=5&keepalives=1&keepalives_idle=5&keepalives_interval=5&keepalives_count=2
SECRET_KEY: long random and secret string
SENTRY: dsn
UPLOAD_FOLDER: /home/arch/uploads
CELERY_CONF:
    BROKER_URL: redis://217.182.87.226/1
    CELERY_RESULT_BACKEND: redis://217.182.87.226/2
LOGGERS:
    stdout:
        level: info
        async: false
    ltsv:
        level: info
        async: true
        host: thot.ovh.com
        port: 12201
        use_tls: true
        static_fields:
            X-OVH-TOKEN-18bc9b: c3dccc6b-0c2e-495e-9f89-86b79247c536
